#!/bin/bash
#Upload a Mondrian schema to Saiku and deploy it to the repository.
set -ex
juju-log "Uploading datasource to server"

report_content=`action-get content`
report_path=`action-get path`

response=$(curl -s -o /dev/null -w "%{http_code}\n" -X POST http://localhost:8080/saiku/rest/saiku/session --data "username=admin&password=admin" -c cookies.txt)

if [ $response -ne 200 ];
then
	curl -s -o /dev/null -w "%{http_code}\n" 'http://localhost:8080/saiku/rest/saiku/session/clear' -H 'Content-Type: application/x-www-form-urlencoded' --data 'username=admin&password=admin' -b cookies.txt
	curl -X POST http://localhost:8080/saiku/rest/saiku/session --data "username=admin&password=admin" -c cookies.txt
fi

curl -b cookies.txt -X POST http://localhost:8080/saiku/rest/saiku/api/repository/resource -d "content=$report_content&file=$report_path"

action-set outcome="finished"